// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhDvlMo7MEu_2SBy58yZY9HdGjfSSiYSs',
    appId: '1:246773894709:web:c4d4d005ec66432a33ab7c',
    messagingSenderId: '246773894709',
    projectId: 'project-d22bed42-f302-4e23-8dc',
    authDomain: 'project-d22bed42-f302-4e23-8dc.firebaseapp.com',
    storageBucket: 'project-d22bed42-f302-4e23-8dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkgBCw9cDyZReIU02mb07Lc9Qkzx8-PI',
    appId: '1:246773894709:android:51f0e5997ef9635b33ab7c',
    messagingSenderId: '246773894709',
    projectId: 'project-d22bed42-f302-4e23-8dc',
    storageBucket: 'project-d22bed42-f302-4e23-8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXm4g-rZsnshGYr1BeMsN_1De5QbKHYLA',
    appId: '1:246773894709:ios:f4ac285fc1d20c3f33ab7c',
    messagingSenderId: '246773894709',
    projectId: 'project-d22bed42-f302-4e23-8dc',
    storageBucket: 'project-d22bed42-f302-4e23-8dc.firebasestorage.app',
    iosClientId: '246773894709-70j994qk62rpn8ook12v1kfhm6f0cq8q.apps.googleusercontent.com',
    iosBundleId: 'org.nitksaa.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXm4g-rZsnshGYr1BeMsN_1De5QbKHYLA',
    appId: '1:246773894709:ios:f4ac285fc1d20c3f33ab7c',
    messagingSenderId: '246773894709',
    projectId: 'project-d22bed42-f302-4e23-8dc',
    storageBucket: 'project-d22bed42-f302-4e23-8dc.firebasestorage.app',
    iosClientId: '246773894709-70j994qk62rpn8ook12v1kfhm6f0cq8q.apps.googleusercontent.com',
    iosBundleId: 'org.nitksaa.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhDvlMo7MEu_2SBy58yZY9HdGjfSSiYSs',
    appId: '1:246773894709:web:346987865cd7f33933ab7c',
    messagingSenderId: '246773894709',
    projectId: 'project-d22bed42-f302-4e23-8dc',
    authDomain: 'project-d22bed42-f302-4e23-8dc.firebaseapp.com',
    storageBucket: 'project-d22bed42-f302-4e23-8dc.firebasestorage.app',
  );
}
